baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

#theme = 'ananke'
theme = 'terminal'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  searchHidenTime = 5